# Project Name
TARGET = osciloscil_patch_init

USE_FATFS = 1

# Sources
CPP_SOURCES = osciloscil_patch_sm.cpp

# Library Locations
LIBDAISY_DIR = libDaisy
DAISYSP_DIR = DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
